export default function Head() {
  return (
    <>
      <title>Well Well Well</title>
      <meta name="description" content="Generated by create-wc-dapp" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
